### PR TITLE
Fix for Kubernetes 1.16 regarding datetime comparison

### LINKED ISSUE #354: kubespawner stopped working after kubernetes upgrade from 1.15 to 1.16
```
[E 2019-09-25 05:16:53.998 JupyterHub web:1788] Uncaught exception GET /hub/user/apoliakevitch/ (10.244.4.1)
    HTTPServerRequest(protocol='http', host='conda.corp-apps.com', method='GET', uri='/hub/user/apoliakevitch/', version='HTTP/1.1', remote_ip='10.244.4.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 1013, in get
        raise copy.copy(exc).with_traceback(exc.__traceback__)
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 589, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 636, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1636, in _start
        events = self.events
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1491, in events
        for event in self.event_reflector.events:
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 72, in events
        key=lambda x: x.last_timestamp,
    TypeError: '<' not supported between instances of 'datetime.datetime' and 'NoneType'
```

### PR DESCRIPTION
**Pull request by consideRatio**
Tested to work on z2jh with k8s 1.13-1.16!

Thanks @stv0g for demonstrating the fix in https://github.com/stv0g/kubespawner/commit/795167b98e548347bf75fd8b18def1e7cea0c901

Closes #357
Closes #354

## About CI changes
I ran into CI failures that was caused by a new release of kubernetes-client/python 11.0.0b1, I also lacked testing of version 9 and 10 of this client, so I fixed them for my current DX.

## Review
- Do we really want to sort the events at all now that we don't always have timestamp information? @bitnik can you give your input on this?

## Open questions
What kind of events that doesn't come with this timestamp value, and why? Here are examples: https://github.com/jupyterhub/kubespawner/issues/354#issuecomment-538203621

### CODE REVIEW

**Comment by betatim** [comment]
Yes we want to sort. I think most of the time these events are used as "log output" to show progress so they should be chronological. There is also https://github.com/jupyterhub/kubespawner/blob/7ebd0c196fff55d2bd9266dd5131bad18de141a7/kubespawner/spawner.py#L1521-L1524 which relies on events being sorted as a way to skip events its already seen.

Maybe we could change it but I think that would be a bigger undertaking.

If we had a good list of the events that have no timestamp we could decide to remove them from the event stream. Depends on what kinds of events they are. From the example you linked I'd be Ok with removing the events shown there from the stream before trying to sort.

Could you briefly explain why all the CI related changes are in this PR and what they achieve?

**Comment by consideRatio** [comment]
@betatim ah nice idea of considering removing events without timestamp, it would be great to learn more about what kind of events that lack timestamps.

@betatim I updated the main post with a note on the CI changes commit. Do you want me to extract it to a separate PR?

**Comment by manics** [comment]
Code change looks fine based on Travis passing on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1483/commits/9a26b4cda6d9445ee95daede2cc3e8964c9db0ef

**Comment by consideRatio** [comment]
Merge? The errors in the pipeline are unrelated.

**Comment by manics** [comment]
If you're happy with https://github.com/jupyterhub/kubespawner/pull/369 merge that and re-trigger travis before merging this?

**Comment by manics** [comment]
@consideRatio Awesome!

**Pull request merged**
