### PR TITLE
add jupyter image spec environment variable

### LINKED ISSUE #182: Expose binder/notebook image name via environment variable to notebook container
*Note: this issue has a twin: https://github.com/jupyterhub/binderhub/issues/586*

I would like to find a way to expose the name (e.g. a GCR or dockerhub path) of the built docker image in the notebook environment. I want to do this because I'd like to give the name of this docker image to `dask-kubernetes` to support scaling computations done in a binder notebook across a larger kubernetes cluster.

I have looked at the current environment variables but it doesn't seem like this functionality is covered yet. 

(more discussion on the larger use case and progress related to this issue here: https://github.com/pangeo-data/pangeo/issues/283)

cc @betatim, @choldgraf, @katekinsman

### PR DESCRIPTION
**Pull request by jhamman**
closes #182 

Note: I have not tested this for my use case yet. @betatim suggested this course of action, and I'm putting it up here for initial comments/redirections while I proceed with testing my binder implementation.

### CODE REVIEW

**Comment by betatim** [comment]
Looks good to me. I had a quick look at the tests in kubespawner and there is only one set testing the `make_pod` functions it seems. So maybe we don't need to add a test for this?

Because I suggested this approach it would be good to get someone else to take a look at this too before hitting the merge button.

**Comment by jhamman** [comment]
pinging @yuvipanda for a quick look

**Comment by yuvipanda** [comment]
LGTM, Thanks @jhamman / @betatim

**Comment by jhamman** [comment]
Thanks @yuvipanda / @betatim!

**Comment by jhamman** [comment]
Might I ask for a version bump in the nearish-term?

**Pull request merged**
