### PR TITLE
Add Sphinx docs

### PR DESCRIPTION
**Pull request by willingc**
[Rendering of WIP docs](http://test-kubespawner.readthedocs.io/en/doc-skeleton/utils.html)

### CODE REVIEW

**Comment by yuvipanda** [comment]
This looks like a great start, @willingc!

**Comment by willingc** [comment]
@yuvipanda I've taken the docs out of WIP adding docs for all of the functions and a subset of the README as an overview. 

To get Travis to not error on install of the spawner and test runs, I made some changes to the `.travis.yml` and `setup.py` as well as adding a `dev-requirements.txt` for testing. Feel free to delete if you can get Travis to run without these changes.

**Comment by yuvipanda** [comment]
@willingc awesome! Do you know if this will also pick out the help text for each traitlet? I guess that's 'user documentation' that we should try to autogenerate...

**Comment by willingc** [comment]
As written, it does not. Let's merge this and do the traitlets in a separate PR. To clarify, when you say help text for traitlet, do you mean the help text for each attribute in the classes in `reflector.py` and `spawner.py`?

**Comment by yuvipanda** [comment]
Thanks @willingc!

Yup, that's what I meant. It's what allows users to configure kubespawner however they want, and should be our 'reference documentation' I guess.

**Comment by willingc** [comment]
Will see if I can get to this on Monday. Thanks for clarifying.

**Pull request merged**
