### PR TITLE
More idiomatic python syntax

### PR DESCRIPTION
**Pull request by AnotherCodeArtist**
Fixing the K8s 1.16 issue in a more idiomatic way

### CODE REVIEW

**Comment by manics** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1444#issuecomment-541707683
There's a small error in this, it should be either
`x.last_timestamp if x.last_timestamp is not None else datetime.min`
or
`x.last_timestamp.timestamp() if x.last_timestamp is not None else 0`

**Comment by dhirschfeld** [comment]
It's quite a common idiom is to jsut use `or` to coalesce a null:
```
 key=lambda x: x.last_timestamp or datetime.min
```

**Comment by GrahamDumpleton** [comment]
FWIW, may relate to older version of `kubernetes` module being used (I can't necessarily use latest at the moment, need to verify), but seeing the error:

```
  File "/opt/app-root/lib/python3.6/site-packages/kubespawner/spawner.py", line 73, in events
    key=lambda x: x.last_timestamp if x.last_timestamp is not None else 0.,
TypeError: '<' not supported between instances of 'float' and 'datetime.datetime'
```

in relation to this code.

It actually predates this change though as old code would also blow up as well.

```
  File "/opt/app-root/lib/python3.6/site-packages/kubespawner/spawner.py", line 72, in events
    key=lambda x: x.last_timestamp,
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

Still trying to understand why.

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:37:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by GrahamDumpleton** [comment]
Okay. Relates to https://github.com/jupyterhub/kubespawner/issues/354

**Pull request merged**
