### PR TITLE
[bufix] Allow POST requests without profile_options specified (defaults will be used)

### PR DESCRIPTION
**Pull request by GeorgianaElena**
This is a test that reproduces the bug in https://github.com/jupyterhub/kubespawner/issues/758.

It should help us find the bug by investigating the particularities of this test profile list and also know if we'd fix the bug.

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
I believe the issue was that we were validating user's chosen `user_options`  against the profile's `profile_options`even if the user didn't chose anything, hence `user_options` was empty.

**Review by consideRatio — APPROVED** [review]

**Comment by yuvipanda** [comment]
I just tested this and it works!

**Comment by consideRatio** [comment]
Nice work identifying this @GeorgianaElena!! This looks good!!

**Comment by yuvipanda** [comment]
@consideRatio the docstring became out of date after this PR, I opened https://github.com/jupyterhub/kubespawner/pull/771 to update it.

**Pull request merged**
