### PR TITLE
using user_options in kubespawner

### PR DESCRIPTION
**Pull request by hhuuggoo**
Untested, and no tests written.  Just wanted to get validation that this approach is correct before doing all that.

### CODE REVIEW

**Comment by hhuuggoo** [comment]
Added tests.  Not sure what else is required, but seems to work ok

**Comment by hhuuggoo** [comment]
```
>   request.addfinalizer(lambda: client.delete_namespace(kube_ns, {}))
E   TypeError: delete_namespace() takes 2 positional arguments but 3 were given
tests/conftest.py:49: TypeError
```
The tests are failing with this...  Which I don't believe is related?  Do you guys know what this is about?

Thanks!

**Comment by yuvipanda** [comment]
@hhuuggoo I think the test failures should be fixed by https://github.com/jupyterhub/kubespawner/pull/292

**Comment by hhuuggoo** [comment]
Well so I spoke with @minrk about this - and he pointed out that this could be dangerous (you might not want your users to be able to pass user options)

So not sure if y'all want to close it, or make it so this behavior is off by default?

**Comment by minrk** [comment]
#301 fixes user_options loading to be consistent whether loaded via API or form, and safe by default (i.e. options are not passthrough to kubespawner attributes, they are interpreted by overrideable load_user_options method)

**Pull request merged**
