### PR TITLE
Add support for running with istio using mTLS

### PR DESCRIPTION
**Pull request by JJ11teen**
This is a continuation of: https://github.com/jupyterhub/kubespawner/pull/425

I tried rebasing the existing PR but couldn't figure it without needing to force-push (which I don't think I can do) - hopefully okay to open this instead.

All thanks to @harsimranmaan for the hard yards!

### CODE REVIEW

**Comment by harsimranmaan** [comment]
Thanks @JJ11teen
 Much appreciated

**Comment by bleggett** [comment]
Would like this merged - currently relying on hacked jhub images to get builds with this kubespawner fix.

**Review by bleggett — APPROVED** [review]

**Review by bleggett — COMMENTED** [review]
<s>This is missing the service creation logic from @harsimranmaan's #425 `kubespawner/objects.py` change - correct?

That is required for this to function, unless I'm missing something.</s>

EDIT: NVM, I'm behind the times - service creation is part of upstream now.

Tested - works for me - and looks good to me. @harsimranmaan's fixes have been sitting in PRs for about a year now so I'm with @JJ11teen - let's get this merged, so people like me don't have to manually hack upstream builds to get something that works with Istio.

**Comment by usmcamp0811** [comment]
I would love for this PR to get accepted. I recently had to do some questionable things to get my organizations JH deployment to work with Istio...

**Comment by yuvipanda** [comment]
Apologies for the long wait and review times, @harsimranmaan and @JJ11teen! I've just merged this, thank you all very much for working on this.

Thanks for the ping, @usmcamp0811!

**Pull request merged**
