### PR TITLE
Add changelog for 4.3.0

### PR DESCRIPTION
**Pull request by GeorgianaElena**

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
LGTM! Thanks @GeorgianaElena!!!

I added a commit to make the `[4.3.0]` which is a markdown link have a URL defined in the footer of this document.

**Comment by consideRatio** [comment]
@GeorgianaElena can you as part of getting this PR follow the RELEASE.md instructions to get the 4.3.0 release out?

**Comment by GeorgianaElena** [comment]
> I added a commit to make the [4.3.0] which is a markdown link have a URL defined in the footer of this document.

Ups, I missed that, sorry. Thank you!

> @GeorgianaElena can you as part of getting this PR merged follow the RELEASE.md instructions to get the 4.3.0 release out?

Of course! I'm on to it

**Comment by GeorgianaElena** [comment]
@consideRatio, for some reason, the publish workflow didn't run for the tagged commit. Hmm.. I am looking into it

**Pull request merged**
