### PR TITLE
add KubeTemplateSpawner 

### PR DESCRIPTION
**Pull request by ktong**
To support more flexible configuration for single-user notebook even though configuration does not support in KubeSpawner yet.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Heya! This is great :D But does it need to be a separate spawner? Can you just not add the hook to KubeSpawner itself?

**Comment by ktong** [comment]
First, KubeSpawner could not cover all configurations supported by K8s. Moreover, K8s adds more configuration in each release. Template Spawner enables using any configurations supported by K8s without waiting for change in KubeSpawner.

For example, I used envFrom from 1.6 to set environment variables in notebook pod. It could be set in jupyterhub and pass it to notebook via env_keep. But it's more straightforward by setting in notebook directly.

**Comment by ktong** [comment]
Moreover, writting yaml template is much easy and straightforward than set individual parameters.

**Comment by yuvipanda** [comment]
You can add extra python code in your jupyterhub_config.py file, including setting up a function that can override things in the spawner and customize it directly. So in your jupyterhub_config.py file, you can have:


```python
from kubespawner import KubeSpawner

class CustomSpawner(KubeSpawner):
    def augment_pod(self, pod):
          # Modify pod object
          return pod

c.JupyterHub.spawner_class = CustomSpawner
```

**Comment by yuvipanda** [comment]
This is going to be much more extensible and simpler than using a template language.

**Comment by ktong** [comment]
It needs change docker image, which is separated with K8s yaml file. By the way, below is  jupyterhub_config.py I am using:
```
import os
import yaml


def _load_from_env(prefix):
    """ Load configuration from environment variables which start with prefix.

    :param prefix: The prefix to match name of environment variables
    :type prefix: str
    :return: Environment variables which name starts with prefix
    :rtype: dict
    """
    prefix_upper = prefix.upper()
    prefix_length = len(prefix) + 1
    return {k[prefix_length:].lower(): yaml.safe_load(v)
           for k, v in os.environ.items()
           if k.upper().startswith(prefix_upper + "_")}


def _load_config(config):
    config_string = config if isinstance(config, str) else config.get_value(None)
    prefix = _get_prefix(config_string) if config_string else ""

    if not prefix:
        return

    env = _load_from_env(prefix)
    if env:
        c[prefix].update(env)


def _get_prefix(config):
    try:
        return config[config.rindex('.') + 1:]
    except ValueError:
        return config


# Load config from environment variables
for config in ["Application", "JupyterHub"]:
    _load_config(config)
_load_config(c.JupyterHub.authenticator_class)
_load_config(c.JupyterHub.spawner_class)

# Add service to monitor and cull idle single-user servers
cull_env = _load_from_env("CULL")
if cull_env.get("enabled", True):
    cull_timeout = cull_env.get("timeout", 3600)
    cull_every = cull_env.get("every", 600)
    c.JupyterHub.services.append(
        {
            'name': 'cull-idle',
            'admin': True,
            'command': 'python3 cull_idle_servers.py --timeout={} --cull_every={}'
                .format(cull_timeout, cull_every).split()
        }
    )
```

With jupyterhub_config.py, K8s is able to customize deployment of docker image with envFrom

**Comment by ktong** [comment]
Because we need write yaml for either K8s or helm, writing template is more natural.

**Comment by ktong** [comment]
replaced by #91

**Pull request closed without merging**
