### PR TITLE
Add relevant badges to README.md

### PR DESCRIPTION
**Pull request by consideRatio**
image

### CODE REVIEW

**Comment by betatim** [comment]
Was going to merge this but after restarting the CI jobs I looked at their logs and am confused why they fail :(

**Comment by consideRatio** [comment]
@betatim it relates to the release of 11.0.0b1 of kubernetes-client/python that we rely on. It is also fixed in the commit of #362 where I allow kubernetes==11 to fail. The issue to track this failure is tracked in #366

**Comment by betatim** [comment]
So should we be setting the dependencies in https://github.com/jupyterhub/kubespawner/blob/18847a9cfcccb6e1644d8f3f24c3675a7c5e65b7/setup.py#L17 so that we limit ourselves to https://pypi.org/project/kubernetes/10.0.1/ instead of allowing the beta version?

**Comment by manics** [comment]
Looks like it's a deliberate decision in Travis:
https://github.com/jupyterhub/kubespawner/blob/18847a9cfcccb6e1644d8f3f24c3675a7c5e65b7/.travis.yml#L13-L15

**Comment by consideRatio** [comment]
@manics aha! that explains my confusion about this behavior where 11.0.0b1 was installed!

**Pull request merged**
