### PR TITLE
Add RELEASE.md and utilize bump2version

### LINKED ISSUE #363: Add RELEASE.md
We are missing a RELEASE.md.

This is ongoing work for various other repositories as well, and we may be automating it to release to PyPI on pushed git tags as well.
- [chartpress](https://github.com/jupyterhub/chartpress)
- [configurable-http-proxy](https://github.com/jupyterhub/configurable-http-proxy)
- [oauthenticator](https://github.com/jupyterhub/oauthenticator)
- [jupyter-server-proxy](https://github.com/jupyterhub/oauthenticator)

### PR DESCRIPTION
**Pull request by consideRatio**
This is copy-pasted and adjusted from chartpress.

Closes #363

### CODE REVIEW

**Comment by consideRatio** [comment]
Did I get it right in spawner.py / setup.py?

**Comment by consideRatio** [comment]
@manics and @betatim, could you have a look at this from the python technical perspective what I do in spawner.py and setup.py especially?

**Comment by manics** [comment]
Looks OK to me:
```
$ python3 -mvenv v
$ v/bin/pip install https://github.com/jupyterhub/kubespawner/archive/3ad78084afa58a7e6e3d09e15543c0753665faf3.zip
$ v/bin/pip list|grep kubespawner
jupyterhub-kubespawner 0.10.2.dev0
```
Note `oauthenticator` uses a different way of storing the version: https://github.com/jupyterhub/oauthenticator/blob/3d7840da11a5e0b4af9e38e3045eb10b6e2bc2a7/setup.py#L35-L36
Are you thinking of standardising on the methods used in chartpress?

**Comment by consideRatio** [comment]
@manics, I mainly choose one to copy paste from pretty much, I don't know what best to apply when there are different implementations on how things are done.

This is all the more reason to have one single place where we can figure that out =) Got ideas on what patterns that make the most sense for various reasons?

I copied stuff from this:
https://github.com/jupyterhub/chartpress/blob/ba34a1301f3119a514385a8c63309cbf7f2c87b0/setup.py#L5-L9

**Comment by manics** [comment]
There are 7 different suggested ways! https://packaging.python.org/guides/single-sourcing-package-version/
Since `bump2version` is used there's no disadvantage to duplicating the version in multiple places if that's clearer than reading/parsing a file

**Pull request merged**
