### PR TITLE
Add after_pod_created_hook

### PR DESCRIPTION
**Pull request by dolfinus**
KubeSpawner has `modify_pod_hook` which allows to change pod spec before it will be launched. But there is not hook to access pod after it was created but before spawner's `start` method is already finished.

This hook is useful for creating other K8S objects, like services or ingress, with properly set up `owner_reference` which allows to automatically remove all created objects after pod removal.

### CODE REVIEW

**Comment by consideRatio** [comment]
@dolfinus are there issues that can be closed/resolved by getting this feature merged?

**Comment by dolfinus** [comment]
It may fix #523, but I'm not sure

**Comment by yuvipanda** [comment]
Thanks, @dolfinus!

**Comment by sbernauer** [comment]
Thanks @dolfinus for implementing this! Helped us quite a lot setting up Services for distributed pyspark code

**Pull request merged**
