### PR TITLE
Multi-namespace support, redux

### PR DESCRIPTION
**Pull request by athornton**
WIP; not tested yet.  Just wanted to get something on the table prior to the end of the year.

In this model users will need to request a MultiNamespacedKubeSpawner in order to get multi-namespace support.  That should leave the majority of people who don't need this functionality unaffected.

### CODE REVIEW

**Comment by lresende** [comment]
Where/How is the user namespace created in this scenario?

**Comment by athornton** [comment]
In my current setup, it's created in the LSST-specific logic I have in a helper class (I do it at pod start time).  

I would suggest--if we want to make the K8s object manipulation something the spawner class itself is responsible for--that we add a couple of configurables (like a user-namespace template, and a delete-namespace-on-stop boolean), and do namespace (and ancillary object, which should be another configurable) creation in start(), and teardown (if requested) in stop().

Ancillary object manipulation would be creating, for instance, service accounts, roles, and rolebindings within the user namespace allowing the user to spawn additional containers for things like dask workers or Argo workflows (all of which has implications for the RBAC for the service account the Hub itself runs with).

**Comment by athornton** [comment]
Just added first cut at the namespace manipulation methods.

Hopefully I will be able to start doing some testing early next week.

**Comment by athornton** [comment]
Ooof.  I got fairly far, but was having trouble with the pod and event reflector startup.  Then another massive upstream change seems to have landed....gonna take a bit to rework.

**Comment by athornton** [comment]
Oh dear.  I screwed up the repository something fierce.  Closing this one, followup in #387

**Pull request closed without merging**
