### PR TITLE
Fix progress serialization issue

### PR DESCRIPTION
**Pull request by consideRatio**
Fixes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1501

### CODE REVIEW

**Comment by betatim** [comment]
In some other projects I use something like the following to serialise datetime objects (this is whats failing/why travis is unhappy):

```python
import json

class JSONEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime.datetime):
            return obj.isoformat()
        return super().default(obj)
json._default_encoder = JSONEncoder()
```

but I am not sure this is "the right way" of doing this.

**Comment by manics** [comment]
What uses the raw-event? Would a combination of `event.to_dict()` and converting the datetime field to an iso8601 string work?

**Comment by consideRatio** [comment]
@clkao added it with a motivation that makes sense to me generally in https://github.com/jupyterhub/kubespawner/pull/361.

**Comment by manics** [comment]
```python
v = kubernetes.client.models.V1Event(involved_object={}, metadata={}, event_time=datetime.datetime.now())
d = v.to_dict()
for (k, v) in d.items():
    if isinstance(v, datetime.datetime):
        d[k] = v.isoformat()
```

**Comment by consideRatio** [comment]
manics you have the series field of the event object that van have datetimes in it as well (MicroTime ins the k8s api ref). So it must go deeper if we do this.

**Pull request merged**
