### PR TITLE
Expand environment variables

### PR DESCRIPTION
**Pull request by dolfinus**
In #644 spawner can add extra services after pod creation. To pass created service name, I've tried to set up notebook environment like this:
```python
c.KubeSpawner.environment = {"SPARK_DRIVER_HOST": "jupyter-{username}-spark-driver--{servername}"}
```
But unfortunately, environment variables does not support substitutions. Now they are

### CODE REVIEW

**Comment by yuvipanda** [comment]
I'm trying to understand if this would be a 'breaking' change, as users might already have things like `${SHELL}` in their env vars. Would we produce a syntax error if that were the case? I know they don't expand in kubernetes unless you use `$(SHELL)` as syntax and SHELL is explicitly set in the kubernetes spec, but what happens when these vars are set for `${SHELL}`? 

I think this is the right thing to do and we should land this PR - I just want to understand if this is a breaking change or not so we can label it appropriately.

Thanks a lot for working on this!

**Comment by dolfinus** [comment]
I've changed current implementation to avoid breaking backward compatibility - instead of `.format` `_expand_all` uses `.replace`. For unknown substitutions, spawner will show a warning

**Comment by yuvipanda** [comment]
@dolfinus ah, damn - I think this might break current escaping where you can escape variables with something like `{{username}}` - that renders as just `{username}` instead of being expanded. With this change, those *will* get replaced. So it's gonna break in a different way.

I think the right thing to do is to mark this as a breaking change, and setup `_expand_all` in basically as many places that need it in one go :) What do you think?

**Comment by dolfinus** [comment]
Ok, reverted latest change back

**Review by manics — APPROVED** [review]
Looks great!

**Comment by dolfinus** [comment]
Should I update CHANGELOG, or this will be done after merging?

**Comment by manics** [comment]
Would you mind adding a paragraph to the Changelog now, ideally including brief upgrade/compatibility instructions? It'll help whoever does the next release.

**Comment by dolfinus** [comment]
Ok, please check

**Comment by dolfinus** [comment]
Any updates?

**Comment by yuvipanda** [comment]
Thanks, @dolfinus!

**Pull request merged**
