### PR TITLE
[KubeIngressProxy] Fix 404 error in `add_route`

### PR DESCRIPTION
**Pull request by dolfinus**
Fix for #638

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
Any changes here are not scrutinized as well as changes in KubeSpawner because we lack end to end tests.

Is this tested to work manually?

**Comment by dolfinus** [comment]
Yes, I've triesdto use KubeIngressProxy and got exception while hub startup, which has gone after this fix

**Comment by ealyn** [comment]
@dolfinus I've view the PR and wonder if function delete_route need remove `await`?

**Comment by ealyn** [comment]
> Why?

Oh, I found you have commit the fix #649. Now everything is find.

**Pull request merged**
