### PR TITLE
fix some spurious additions in tests

### PR DESCRIPTION
**Pull request by minrk**
some blocks added due to merge conflicts in #458

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
LGTM!

Merge away if you also think the test failures are unrelated.

**Comment by minrk** [comment]
Unfortunately, this reveals a test failure that appears to have been broken by #458 (reflected pods never get uid, despite having them assigned), but a typo in the PR prevented the affected test from running. I'm going to try to figure that one out for a bit.

**Comment by minrk** [comment]
I think I got it - it was a couple missing updates from pod_name -> ref_key in the internal_ssl block, missed because the internal_ssl test was accidentally being skipped. Should be fine, but let's wait for CI to confirm. Then I'll rebase #473 .

**Comment by consideRatio** [comment]
@minrk thank you for following up thoroughly on this!

**Comment by minrk** [comment]
tests passing

**Pull request merged**
