### PR TITLE
Add changelog for 6.1.0

### LINKED ISSUE #767: Release planning for 6.1.0
KubeSpawner would benefit greatly from a release with #742 in it, what I think was a regression from previous major versions of KubeSpawner. Z2JH 3.0.0 - 3.0.3 users are affected by it. The consequences of this bug is that user pods can be left running in k8s while JupyterHub thinks the servers are stopped, and this can incurr significant cloud costs. Users with a stranded server can still re-start it via JupyterHub though.

To make this release, we should also include notes on how users can cleanup such stranded servers intelligently. @minrk has made [a script that inspects k8s resources and the jupyterhub state](https://gist.github.com/minrk/e15653520847746e643a6ca5e48d3949) to help figure out what user servers should be considered for cleanup.

## Todo

- #702, fixed by #773
- #742
- #785
- #787
- #768

## Todo related to `unlisted_choice`

- #758, fixed by #772
- #756, fixed by #778
- #757

## Todo considered outside the scope of this release

- #775

### PR DESCRIPTION
**Pull request by consideRatio**
I propose that we cut a release now with bugfixes, a performance improvement, and the `unlisted_choice` functionality part of `profile_lists` -> `profile_options`.

- Closes #767

If approved by monday next week, I'll cut a release then.

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
@consideRatio, I think we might want to also fix this https://github.com/jupyterhub/kubespawner/issues/758 as part of a new release. A workaround we've used for this was https://github.com/2i2c-org/infrastructure/pull/2865/files.

**Comment by consideRatio** [comment]
I've not pushed on this as i felt we absolutely need a note in the changelog to help users remediate the consequences of the bug as well - this is the place to make such note.

I plan to test a script by Min tomorrow helping with that, possibly make a smaller tweak, and then link to it from the changelog.

**Comment by shaneknapp** [comment]
@consideRatio thanks for the update!

**Review by yuvipanda — APPROVED** [review]
LGTM

**Pull request merged**
